// protobuf version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: define.proto

package define

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Basic object struct for mul message
type Obj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Obj) Reset() {
	*x = Obj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Obj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obj) ProtoMessage() {}

func (x *Obj) ProtoReflect() protoreflect.Message {
	mi := &file_define_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obj.ProtoReflect.Descriptor instead.
func (*Obj) Descriptor() ([]byte, []int) {
	return file_define_proto_rawDescGZIP(), []int{0}
}

func (x *Obj) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Obj) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HardWareInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac       string `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	OsType    string `protobuf:"bytes,4,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion string `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Version   string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Unid      string `protobuf:"bytes,7,opt,name=unid,proto3" json:"unid,omitempty"`
	Cpu       *Obj   `protobuf:"bytes,8,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Board     *Obj   `protobuf:"bytes,9,opt,name=board,proto3" json:"board,omitempty"`
	Gpu       *Obj   `protobuf:"bytes,10,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Memory    *Obj   `protobuf:"bytes,11,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk      *Obj   `protobuf:"bytes,12,opt,name=disk,proto3" json:"disk,omitempty"`
	Network   *Obj   `protobuf:"bytes,13,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *HardWareInfo) Reset() {
	*x = HardWareInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardWareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardWareInfo) ProtoMessage() {}

func (x *HardWareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_define_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardWareInfo.ProtoReflect.Descriptor instead.
func (*HardWareInfo) Descriptor() ([]byte, []int) {
	return file_define_proto_rawDescGZIP(), []int{1}
}

func (x *HardWareInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *HardWareInfo) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *HardWareInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *HardWareInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HardWareInfo) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *HardWareInfo) GetCpu() *Obj {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *HardWareInfo) GetBoard() *Obj {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *HardWareInfo) GetGpu() *Obj {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *HardWareInfo) GetMemory() *Obj {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *HardWareInfo) GetDisk() *Obj {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *HardWareInfo) GetNetwork() *Obj {
	if x != nil {
		return x.Network
	}
	return nil
}

type HardWareInfo_Other struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Machine string `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	Apt     string `protobuf:"bytes,2,opt,name=apt,proto3" json:"apt,omitempty"`
	Active  string `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *HardWareInfo_Other) Reset() {
	*x = HardWareInfo_Other{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardWareInfo_Other) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardWareInfo_Other) ProtoMessage() {}

func (x *HardWareInfo_Other) ProtoReflect() protoreflect.Message {
	mi := &file_define_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardWareInfo_Other.ProtoReflect.Descriptor instead.
func (*HardWareInfo_Other) Descriptor() ([]byte, []int) {
	return file_define_proto_rawDescGZIP(), []int{1, 0}
}

func (x *HardWareInfo_Other) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *HardWareInfo_Other) GetApt() string {
	if x != nil {
		return x.Apt
	}
	return ""
}

func (x *HardWareInfo_Other) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

var File_define_proto protoreflect.FileDescriptor

var file_define_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x22, 0x2d, 0x0a, 0x03, 0x4f, 0x62, 0x6a, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa1, 0x03, 0x0a, 0x0c, 0x48, 0x61, 0x72, 0x64, 0x57, 0x61,
	0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x73, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x21, 0x0a,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x12, 0x1d, 0x0a, 0x03, 0x67, 0x70, 0x75, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x52, 0x03, 0x67, 0x70, 0x75, 0x12,
	0x23, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x52, 0x06, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x52,
	0x04, 0x64, 0x69, 0x73, 0x6b, 0x12, 0x25, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e,
	0x4f, 0x62, 0x6a, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x1a, 0x4b, 0x0a, 0x05,
	0x4f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_define_proto_rawDescOnce sync.Once
	file_define_proto_rawDescData = file_define_proto_rawDesc
)

func file_define_proto_rawDescGZIP() []byte {
	file_define_proto_rawDescOnce.Do(func() {
		file_define_proto_rawDescData = protoimpl.X.CompressGZIP(file_define_proto_rawDescData)
	})
	return file_define_proto_rawDescData
}

var file_define_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_define_proto_goTypes = []interface{}{
	(*Obj)(nil),                // 0: define.Obj
	(*HardWareInfo)(nil),       // 1: define.HardWareInfo
	(*HardWareInfo_Other)(nil), // 2: define.HardWareInfo.Other
}
var file_define_proto_depIdxs = []int32{
	0, // 0: define.HardWareInfo.cpu:type_name -> define.Obj
	0, // 1: define.HardWareInfo.board:type_name -> define.Obj
	0, // 2: define.HardWareInfo.gpu:type_name -> define.Obj
	0, // 3: define.HardWareInfo.memory:type_name -> define.Obj
	0, // 4: define.HardWareInfo.disk:type_name -> define.Obj
	0, // 5: define.HardWareInfo.network:type_name -> define.Obj
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_define_proto_init() }
func file_define_proto_init() {
	if File_define_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_define_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Obj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardWareInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardWareInfo_Other); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_define_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_define_proto_goTypes,
		DependencyIndexes: file_define_proto_depIdxs,
		MessageInfos:      file_define_proto_msgTypes,
	}.Build()
	File_define_proto = out.File
	file_define_proto_rawDesc = nil
	file_define_proto_goTypes = nil
	file_define_proto_depIdxs = nil
}
